/** Nimbus-owned bootstrap for the ClickHouse Kapa Ask AI widget. */

export {};

declare global {
  interface Window {
    kapaSettings?: { user: { uniqueClientId?: string } };
    Kapa?: { open: (options: { mode: "ai" }) => void };
  }
}

const SCRIPT_ID = "kapa-widget-script";
const SCRIPT_URL = "https://widget.kapa.ai/kapa-widget.bundle.js";
const OPEN_RETRY_INTERVAL_MS = 50;
const OPEN_RETRY_LIMIT = 60;
let pendingOpen = false;
let openRetryTimer: number | undefined;

function cookie(name: string): string | undefined {
  const prefix = `${name}=`;
  for (const value of decodeURIComponent(document.cookie).split(";")) {
    const trimmed = value.trim();
    if (trimmed.startsWith(prefix)) return trimmed.slice(prefix.length);
  }
  return undefined;
}

function googleAnalyticsUserId(): string | undefined {
  const parts = cookie("_ga")?.split(".").slice(-2);
  return parts?.length === 2 ? parts.join("-") : undefined;
}

function isUnsupportedIos(): boolean {
  if (!/iPad|iPhone/.test(navigator.userAgent)) return false;
  const match = navigator.userAgent.match(/OS (\d+)(?:_(\d+))?/);
  if (!match) return true;
  const major = Number.parseInt(match[1], 10);
  const minor = Number.parseInt(match[2] ?? "0", 10);
  return major < 16 || (major === 16 && minor <= 4);
}

function boot(): void {
  if (document.getElementById(SCRIPT_ID) || isUnsupportedIos()) return;

  window.kapaSettings = { user: { uniqueClientId: googleAnalyticsUserId() } };
  const script = document.createElement("script");
  script.id = SCRIPT_ID;
  script.src = SCRIPT_URL;
  script.async = true;
  script.defer = true;
  script.onload = () => {
    if (pendingOpen) openKapa();
  };
  for (const [name, value] of Object.entries({
    "data-website-id": "5df6cc2b-732e-44e4-b789-aec81b70fe46",
    "data-project-name": "ClickHouse",
    "data-project-color": "#151515",
    "data-project-logo":
      "https://avatars.githubusercontent.com/u/54801242?s=200&v=4",
    "data-modal-disclaimer":
      "This is a custom LLM for ClickHouse with access to all developer documentation, open GitHub Issues, YouTube videos, and resolved StackOverflow posts. Please note that answers are generated by AI and may not be fully accurate, so please use your best judgement.",
    "data-modal-example-questions":
      "How to speed up queries?,How to use materialized views?",
    "data-mcp-enabled": "false",
    "data-launcher-button-hidden": "true",
  })) {
    script.setAttribute(name, value);
  }
  document.head.appendChild(script);
}

function openKapa(): void {
  if (window.Kapa) {
    if (openRetryTimer !== undefined) {
      window.clearInterval(openRetryTimer);
      openRetryTimer = undefined;
    }
    pendingOpen = false;
    window.Kapa.open({ mode: "ai" });
    return;
  }

  pendingOpen = true;
  boot();
  if (openRetryTimer !== undefined) return;

  let attempts = 0;
  openRetryTimer = window.setInterval(() => {
    attempts += 1;
    if (window.Kapa) {
      openKapa();
    } else if (attempts >= OPEN_RETRY_LIMIT) {
      window.clearInterval(openRetryTimer);
      openRetryTimer = undefined;
      pendingOpen = false;
    }
  }, OPEN_RETRY_INTERVAL_MS);
}

document.addEventListener(
  "pointerdown",
  (event) => {
    if (!event.isPrimary || event.button !== 0) return;
    if (
      !(event.target as Element | null)?.closest(
        "[data-kapa-trigger][data-sidebar-tool]",
      )
    )
      return;
    openKapa();
  },
  true,
);

document.addEventListener("click", (event) => {
  const trigger = (event.target as Element | null)?.closest(
    "[data-kapa-trigger]",
  );
  if (!trigger) return;
  // Pointer activation of the sidebar control opens on pointerdown; retain
  // click for keyboard activation and non-sidebar triggers.
  if (trigger.hasAttribute("data-sidebar-tool") && event.detail > 0) return;
  event.preventDefault();
  openKapa();
});

if (document.readyState === "loading")
  document.addEventListener("DOMContentLoaded", boot, { once: true });
else boot();
