// AUTO-GENERATED by _site/scripts/update_kb.py — do not edit by hand.
// Re-run the script to refresh the knowledge-base index.
export const kbIndex = {
  "categories": [
    "Cloud",
    "Configuración e instalación",
    "Configuración y ajustes",
    "Consultas y SQL",
    "General y preguntas frecuentes",
    "Gestión de datos",
    "Importación y exportación de datos",
    "Integraciones y bibliotecas de cliente",
    "Monitorización y depuración",
    "Rendimiento y optimización",
    "Resolución de problemas y errores",
    "Seguridad y control de acceso",
    "Tablas y esquema",
    "Vistas materializadas y proyecciones"
  ],
  "tags": [
    "Administración de Cloud",
    "Administración de servidores",
    "Administración del servidor",
    "Casos de uso",
    "Clientes de lenguaje",
    "Clientes e interfaces nativos",
    "Clientes nativos e interfaces",
    "Comunidad",
    "Conceptos",
    "Conceptos básicos de datos",
    "Conceptos fundamentales de datos",
    "Conceptos fundamentales de los datos",
    "Configuración",
    "Errores y excepciones",
    "Exportación de datos",
    "Formatos de datos",
    "Fuentes de datos",
    "Funciones",
    "Gestión de Cloud",
    "Gestión de datos",
    "Herramientas y utilidades",
    "Implementaciones y escalado",
    "Ingestión de datos",
    "Modelado de datos",
    "Rendimiento y optimizaciones",
    "Rendimiento y optimización",
    "Runbooks",
    "SETTING",
    "Seguridad y autenticación",
    "Settings",
    "Solución de problemas",
    "Tablas del sistema",
    "buenas prácticas"
  ],
  "articles": [
    {
      "id": "configuration-settings/about-quotas-and-query-complexity",
      "title": "Acerca de las cuotas y la complejidad de las consultas",
      "description": "Las cuotas y la complejidad de las consultas son mecanismos eficaces para limitar y restringir lo que los usuarios pueden hacer en ClickHouse. Este artículo de la base de conocimientos muestra ejemplos de cómo aplicar estos dos enfoques.",
      "href": "/es/resources/support-center/knowledge-base/configuration-settings/about-quotas-and-query-complexity",
      "category": "Configuración y ajustes",
      "tags": [
        "Gestión de Cloud"
      ]
    },
    {
      "id": "security/windows-active-directory-to-ch-roles",
      "title": "Asignación de grupos de seguridad de Active Directory de Windows a roles de ClickHouse",
      "description": "Ejemplo de asignación de grupos de seguridad de Active Directory de Windows a roles de ClickHouse",
      "href": "/es/resources/support-center/knowledge-base/security/windows-active-directory-to-ch-roles",
      "category": "Seguridad y control de acceso",
      "tags": [
        "Herramientas y utilidades"
      ]
    },
    {
      "id": "tables-schema/add-column",
      "title": "Añadir una columna a una tabla",
      "description": "En esta guía, aprenderemos a añadir una columna a una tabla existente.",
      "href": "/es/resources/support-center/knowledge-base/tables-schema/add-column",
      "category": "Tablas y esquema",
      "tags": [
        "Modelado de datos"
      ]
    },
    {
      "id": "tables-schema/search-across-node-for-tables-with-a-wildcard",
      "title": "Buscar tablas en todos los nodos con un comodín",
      "description": "Aprende a buscar en todos los nodos tablas con un comodín.",
      "href": "/es/resources/support-center/knowledge-base/tables-schema/search-across-node-for-tables-with-a-wildcard",
      "category": "Tablas y esquema",
      "tags": [
        "Implementaciones y escalado"
      ]
    },
    {
      "id": "queries-sql/calculate-pi-using-sql",
      "title": "Calculemos pi con SQL",
      "description": "¡Es el Día de Pi! Calculemos pi con ClickHouse SQL",
      "href": "/es/resources/support-center/knowledge-base/queries-sql/calculate-pi-using-sql",
      "category": "Consultas y SQL",
      "tags": [
        "Casos de uso"
      ]
    },
    {
      "id": "configuration-settings/change-the-prompt-in-clickhouse-client",
      "title": "Cambiar el prompt en clickhouse-client",
      "description": "Este artículo explica cómo cambiar el prompt en tu cliente de ClickHouse y en la ventana de terminal de clickhouse-local de :) a un prefijo seguido de :)",
      "href": "/es/resources/support-center/knowledge-base/configuration-settings/change-the-prompt-in-clickhouse-client",
      "category": "Configuración y ajustes",
      "tags": [
        "Configuración",
        "Clientes nativos e interfaces"
      ]
    },
    {
      "id": "monitoring-debugging/send-logs-level",
      "title": "Capturar los logs del servidor de las consultas en el cliente",
      "description": "Aprende a capturar los logs del servidor en el cliente, incluso con distintas configuraciones de registro, mediante la configuración de cliente `send_logs_level`.",
      "href": "/es/resources/support-center/knowledge-base/monitoring-debugging/send-logs-level",
      "category": "Monitorización y depuración",
      "tags": [
        "Administración del servidor"
      ]
    },
    {
      "id": "queries-sql/comparing-metrics-between-queries",
      "title": "Comparar métricas entre consultas en decibelios",
      "description": "Una consulta para comparar métricas entre dos consultas en ClickHouse.",
      "href": "/es/resources/support-center/knowledge-base/queries-sql/comparing-metrics-between-queries",
      "category": "Consultas y SQL",
      "tags": [
        "Rendimiento y optimización"
      ]
    },
    {
      "id": "data-management/understanding-part-types-and-storage-formats",
      "title": "Comprender los tipos de partes y los formatos de almacenamiento",
      "description": "Conozca los distintos tipos de partes (Wide vs Compact) y formatos de almacenamiento (Full vs Packed) en ClickHouse, y cómo afectan el rendimiento.",
      "href": "/es/resources/support-center/knowledge-base/data-management/understanding-part-types-and-storage-formats",
      "category": "Gestión de datos",
      "tags": [
        "Conceptos fundamentales de datos"
      ]
    },
    {
      "id": "cloud-services/confluent-cloud-private-connectivity-for-clickpipes",
      "title": "Conectividad privada de Confluent Cloud para ClickPipes",
      "description": "Cómo conectar ClickPipes a un clúster de Kafka existente de Confluent Cloud mediante AWS PrivateLink o GCP Private Service Connect.",
      "href": "/es/resources/support-center/knowledge-base/cloud-services/confluent-cloud-private-connectivity-for-clickpipes",
      "category": "Cloud",
      "tags": [
        "Seguridad y autenticación",
        "Administración de Cloud"
      ]
    },
    {
      "id": "setup-installation/set-up-clickhouse-documentation-mcp-server",
      "title": "Configura el servidor MCP de documentación de ClickHouse",
      "description": "Conecta herramientas de IA a la documentación de ClickHouse mediante el Model Context Protocol.",
      "href": "/es/resources/support-center/knowledge-base/setup-installation/set-up-clickhouse-documentation-mcp-server",
      "category": "Configuración e instalación",
      "tags": [
        "Herramientas y utilidades"
      ]
    },
    {
      "id": "cloud-services/aws-privatelink-setup-for-msk-clickpipes",
      "title": "Configuración de AWS PrivateLink para exponer MSK a ClickPipes",
      "description": "Pasos para exponer un MSK privado mediante la conectividad multi-VPC de MSK a ClickPipes.",
      "href": "/es/resources/support-center/knowledge-base/cloud-services/aws-privatelink-setup-for-msk-clickpipes",
      "category": "Cloud",
      "tags": [
        "Seguridad y autenticación",
        "Administración de Cloud"
      ]
    },
    {
      "id": "cloud-services/aws-privatelink-setup-for-clickpipes",
      "title": "Configuración de AWS PrivateLink para exponer una instancia de RDS privada a ClickPipes",
      "description": "Pasos de configuración para exponer una instancia de RDS privada a ClickPipes mediante AWS PrivateLink.",
      "href": "/es/resources/support-center/knowledge-base/cloud-services/aws-privatelink-setup-for-clickpipes",
      "category": "Cloud",
      "tags": [
        "Seguridad y autenticación",
        "Gestión de Cloud"
      ]
    },
    {
      "id": "troubleshooting/configure-cap-ipc-lock-and-cap-sys-nice-in-docker",
      "title": "Configuración de las capacidades CAP_IPC_LOCK y CAP_SYS_NICE en Docker",
      "description": "Aprende a resolver las advertencias de Docker sobre las capacidades `CAP_IPC_LOCK` y `CAP_SYS_NICE` al ejecutar ClickHouse en un contenedor.",
      "href": "/es/resources/support-center/knowledge-base/troubleshooting/configure-cap-ipc-lock-and-cap-sys-nice-in-docker",
      "category": "Resolución de problemas y errores",
      "tags": [
        "Errores y excepciones"
      ]
    },
    {
      "id": "performance-optimization/tips-tricks-optimizing-basic-data-types-in-clickhouse",
      "title": "Consejos y trucos para optimizar tipos de datos básicos en ClickHouse",
      "description": "Consejos y trucos para optimizar tipos de datos básicos en ClickHouse",
      "href": "/es/resources/support-center/knowledge-base/performance-optimization/tips-tricks-optimizing-basic-data-types-in-clickhouse",
      "category": "Rendimiento y optimización",
      "tags": [
        "Rendimiento y optimizaciones"
      ]
    },
    {
      "id": "security/common-rbac-queries",
      "title": "Consultas habituales de RBAC",
      "description": "Consultas para otorgar permisos específicos a los usuarios.",
      "href": "/es/resources/support-center/knowledge-base/security/common-rbac-queries",
      "category": "Seguridad y control de acceso",
      "tags": [
        "Seguridad y autenticación",
        "Administración de Cloud"
      ]
    },
    {
      "id": "queries-sql/useful-queries-for-troubleshooting",
      "title": "Consultas útiles para solucionar problemas",
      "description": "Una colección de consultas prácticas para solucionar problemas de ClickHouse, que incluye cómo supervisar el tamaño de las tablas, las consultas de larga duración y los errores.",
      "href": "/es/resources/support-center/knowledge-base/queries-sql/useful-queries-for-troubleshooting",
      "category": "Consultas y SQL",
      "tags": [
        "Settings"
      ]
    },
    {
      "id": "data-management/backing-up-a-specific-partition",
      "title": "Copia de seguridad de una partición específica",
      "description": "¿Cómo puedo hacer una copia de seguridad de una partición específica en ClickHouse?",
      "href": "/es/resources/support-center/knowledge-base/data-management/backing-up-a-specific-partition",
      "category": "Gestión de datos",
      "tags": [
        "Gestión de datos"
      ]
    },
    {
      "id": "monitoring-debugging/mapping-of-system-metrics-to-prometheus-metrics",
      "title": "Correspondencia de las métricas utilizadas en system.dashboards a las métricas de Prometheus en `system.custom_metrics`",
      "description": "Correspondencia de las métricas utilizadas en system.dashboards a las métricas de Prometheus en system.custom_metrics",
      "href": "/es/resources/support-center/knowledge-base/monitoring-debugging/mapping-of-system-metrics-to-prometheus-metrics",
      "category": "Monitorización y depuración",
      "tags": [
        "Tablas del sistema"
      ]
    },
    {
      "id": "cloud-services/custom-dns-alias-for-instance",
      "title": "Crear un alias DNS personalizado mediante la configuración de un proxy inverso",
      "description": "Aprenda a configurar un alias DNS personalizado para su instancia mediante un proxy inverso",
      "href": "/es/resources/support-center/knowledge-base/cloud-services/custom-dns-alias-for-instance",
      "category": "Cloud",
      "tags": [
        "Administración del servidor",
        "Seguridad y autenticación"
      ]
    },
    {
      "id": "setup-installation/how-to-increase-thread-pool-size",
      "title": "Cómo aumentar el número de hilos en ClickHouse",
      "description": "Aprende a configurar el Global Thread pool de ClickHouse ajustando parámetros como `max_thread_pool_size`, `thread_pool_queue_size` y `max_thread_pool_free_size`.",
      "href": "/es/resources/support-center/knowledge-base/setup-installation/how-to-increase-thread-pool-size",
      "category": "Configuración e instalación",
      "tags": [
        "Rendimiento y optimización"
      ]
    },
    {
      "id": "data-management/calculate-ratio-of-zero-sparse-serialization",
      "title": "Cómo calcular la proporción de valores vacíos o cero en cada columna de una tabla",
      "description": "Aprenda a calcular la proporción de valores vacíos o cero en cada columna de una tabla de ClickHouse para optimizar la serialización de columnas dispersas.",
      "href": "/es/resources/support-center/knowledge-base/data-management/calculate-ratio-of-zero-sparse-serialization",
      "category": "Gestión de datos",
      "tags": [
        "Rendimiento y optimizaciones"
      ]
    },
    {
      "id": "setup-installation/llvm-clang-up-to-date",
      "title": "Cómo compilar LLVM y clang en Linux",
      "description": "Comandos para compilar LLVM y clang en Linux.",
      "href": "/es/resources/support-center/knowledge-base/setup-installation/llvm-clang-up-to-date",
      "category": "Configuración e instalación",
      "tags": [
        "Comunidad",
        "Herramientas y utilidades"
      ]
    },
    {
      "id": "cloud-services/how-to-check-my-clickhouse-cloud-sevice-state",
      "title": "Cómo comprobar el estado de tu servicio de ClickHouse Cloud",
      "description": "Aprende a usar la ClickHouse Cloud API para comprobar si tu servicio está detenido, inactivo o en ejecución sin reactivarlo.",
      "href": "/es/resources/support-center/knowledge-base/cloud-services/how-to-check-my-clickhouse-cloud-sevice-state",
      "category": "Cloud",
      "tags": [
        "Gestión de Cloud"
      ]
    },
    {
      "id": "security/check-users-roles",
      "title": "Cómo comprobar qué usuarios están asignados a roles y viceversa",
      "description": "Aprende a consultar `system.role_grants` de ClickHouse para ver qué usuarios están asignados a roles y qué roles están asignados a usuarios específicos.",
      "href": "/es/resources/support-center/knowledge-base/security/check-users-roles",
      "category": "Seguridad y control de acceso",
      "tags": [
        "Administración de servidores",
        "Tablas del sistema",
        "Administración de Cloud"
      ]
    },
    {
      "id": "cloud-services/how-to-connect-to-ch-cloud-using-ssh-keys",
      "title": "Cómo conectarse a ClickHouse con claves SSH",
      "description": "Cómo conectarse a ClickHouse y ClickHouse Cloud con claves SSH",
      "href": "/es/resources/support-center/knowledge-base/cloud-services/how-to-connect-to-ch-cloud-using-ssh-keys",
      "category": "Cloud",
      "tags": [
        "Administración de Cloud",
        "Seguridad y autenticación"
      ]
    },
    {
      "id": "integrations/how-to-set-up-ch-on-docker-odbc-connect-mssql",
      "title": "Cómo configurar ClickHouse en Docker con ODBC para conectarse a una base de datos de Microsoft SQL Server (MSSQL)",
      "description": "Cómo configurar ClickHouse en Docker con ODBC para conectarse a una base de datos de Microsoft SQL Server (MSSQL)",
      "href": "/es/resources/support-center/knowledge-base/integrations/how-to-set-up-ch-on-docker-odbc-connect-mssql",
      "category": "Integraciones y bibliotecas de cliente",
      "tags": [
        "Clientes e interfaces nativos"
      ]
    },
    {
      "id": "configuration-settings/configure-a-user-setting",
      "title": "Cómo configurar SETTING para un usuario en ClickHouse",
      "description": "Aprende a definir SETTING en ClickHouse para consultas individuales, sesiones de cliente o usuarios específicos mediante los comandos `SET` y `ALTER USER`.",
      "href": "/es/resources/support-center/knowledge-base/configuration-settings/configure-a-user-setting",
      "category": "Configuración y ajustes",
      "tags": [
        "SETTING"
      ]
    },
    {
      "id": "data-management/dictionary-using-strings",
      "title": "Cómo crear un Diccionario de ClickHouse con claves y valores de tipo String",
      "description": "Aprende a crear un diccionario de ClickHouse con claves y valores de tipo String a partir de una tabla MergeTree como origen, con ejemplos de configuración y uso.",
      "href": "/es/resources/support-center/knowledge-base/data-management/dictionary-using-strings",
      "category": "Gestión de datos",
      "tags": [
        "Modelado de datos"
      ]
    },
    {
      "id": "tables-schema/how-to-create-table-to-query-multiple-remote-clusters",
      "title": "Cómo crear una tabla que permita consultar varios clústeres remotos",
      "description": "Cómo crear una tabla que permita consultar varios clústeres remotos",
      "href": "/es/resources/support-center/knowledge-base/tables-schema/how-to-create-table-to-query-multiple-remote-clusters",
      "category": "Tablas y esquema",
      "tags": [
        "Implementaciones y escalado"
      ]
    },
    {
      "id": "cloud-services/opt-out-core-dump-collection",
      "title": "Cómo desactivar la recopilación de informes de fallos",
      "description": "En este artículo se muestra cómo desactivar la recopilación de informes de fallos en ClickHouse Cloud",
      "href": "/es/resources/support-center/knowledge-base/cloud-services/opt-out-core-dump-collection",
      "category": "Cloud",
      "tags": [
        "Gestión de Cloud"
      ]
    },
    {
      "id": "monitoring-debugging/outputSendLogsLevelTracesToFile",
      "title": "Cómo enviar a un archivo trazas de nivel de registros usando clickhouse-client",
      "description": "Cómo enviar a un archivo trazas de nivel de registros usando clickhouse-client",
      "href": "/es/resources/support-center/knowledge-base/monitoring-debugging/outputSendLogsLevelTracesToFile",
      "category": "Monitorización y depuración",
      "tags": [
        "Exportación de datos"
      ]
    },
    {
      "id": "data-import-export/file-export",
      "title": "Cómo exportar datos de ClickHouse a un archivo",
      "description": "Conozca varios métodos para exportar datos de ClickHouse, incluidos `INTO OUTFILE`, el motor de tabla File y la redirección en la línea de comandos.",
      "href": "/es/resources/support-center/knowledge-base/data-import-export/file-export",
      "category": "Importación y exportación de datos",
      "tags": [
        "Exportación de datos"
      ]
    },
    {
      "id": "data-import-export/mysql-to-parquet-csv-json",
      "title": "Cómo exportar datos de MySQL a Parquet, CSV o JSON con ClickHouse",
      "description": "Aprende a usar la herramienta `clickhouse-local` para exportar datos de MySQL a formatos como Parquet, CSV o JSON de forma rápida y eficiente.",
      "href": "/es/resources/support-center/knowledge-base/data-import-export/mysql-to-parquet-csv-json",
      "category": "Importación y exportación de datos",
      "tags": [
        "Formatos de datos",
        "Exportación de datos"
      ]
    },
    {
      "id": "monitoring-debugging/generate-har-file",
      "title": "Cómo generar un archivo HAR para soporte técnico",
      "description": "Un archivo HAR (HTTP Archive) registra la actividad de red en su navegador. Puede ayudar a nuestro equipo de soporte técnico a diagnosticar cargas de página lentas, solicitudes fallidas u otros problemas de red.",
      "href": "/es/resources/support-center/knowledge-base/monitoring-debugging/generate-har-file",
      "category": "Monitorización y depuración",
      "tags": [
        "Herramientas y utilidades"
      ]
    },
    {
      "id": "setup-installation/enabling-ssl-with-lets-encrypt",
      "title": "Cómo habilitar SSL con Let's Encrypt en un solo servidor de ClickHouse",
      "description": "Aprenda a configurar SSL para un solo servidor de ClickHouse con Let's Encrypt, incluida la emisión de certificados, la configuración y la validación.",
      "href": "/es/resources/support-center/knowledge-base/setup-installation/enabling-ssl-with-lets-encrypt",
      "category": "Configuración e instalación",
      "tags": [
        "Seguridad y autenticación"
      ]
    },
    {
      "id": "materialized-views/how-to-display-queries-using-mv",
      "title": "Cómo identificar consultas que utilizan vistas materializadas en ClickHouse",
      "description": "Aprende a consultar los registros de ClickHouse para identificar todas las consultas que involucran vistas materializadas dentro de un intervalo de tiempo determinado.",
      "href": "/es/resources/support-center/knowledge-base/materialized-views/how-to-display-queries-using-mv",
      "category": "Vistas materializadas y proyecciones",
      "tags": [
        "Tablas del sistema"
      ]
    },
    {
      "id": "performance-optimization/find-expensive-queries",
      "title": "Cómo identificar las consultas más costosas en ClickHouse",
      "description": "Aprende a usar la tabla `query_log` de ClickHouse para identificar las consultas con mayor consumo de memoria y CPU en nodos distribuidos.",
      "href": "/es/resources/support-center/knowledge-base/performance-optimization/find-expensive-queries",
      "category": "Rendimiento y optimización",
      "tags": [
        "Rendimiento y optimización"
      ]
    },
    {
      "id": "configuration-settings/ignoring-incorrect-settings",
      "title": "Cómo ignorar ajustes incorrectos en ClickHouse",
      "description": "Aprenda a usar la opción `skip_check_for_incorrect_settings` para permitir que ClickHouse se inicie incluso cuando los ajustes de nivel de usuario se especifiquen incorrectamente.",
      "href": "/es/resources/support-center/knowledge-base/configuration-settings/ignoring-incorrect-settings",
      "category": "Configuración y ajustes",
      "tags": [
        "Configuración"
      ]
    },
    {
      "id": "data-import-export/ingest-parquet-files-in-s3",
      "title": "Cómo ingestar archivos Parquet desde un bucket de S3",
      "description": "Aprende los conceptos básicos del uso del motor de tabla S3 en ClickHouse para ingestar y consultar archivos Parquet desde un bucket de S3, incluida la configuración, los permisos de acceso y ejemplos de importación de datos.",
      "href": "/es/resources/support-center/knowledge-base/data-import-export/ingest-parquet-files-in-s3",
      "category": "Importación y exportación de datos",
      "tags": [
        "Ingestión de datos"
      ]
    },
    {
      "id": "data-import-export/kafka-to-clickhouse-setup",
      "title": "Cómo ingestar datos de Kafka en ClickHouse",
      "description": "Aprende a ingestar datos de un topic de Kafka en ClickHouse mediante el motor de tabla Kafka, vistas materializadas y tablas MergeTree.",
      "href": "/es/resources/support-center/knowledge-base/data-import-export/kafka-to-clickhouse-setup",
      "category": "Importación y exportación de datos",
      "tags": [
        "Ingestión de datos"
      ]
    },
    {
      "id": "performance-optimization/check-query-processing-time-only",
      "title": "Cómo medir el tiempo de procesamiento de consultas sin devolver filas",
      "description": "Aprende a usar la opción `FORMAT Null` de ClickHouse para medir el tiempo de procesamiento de consultas sin devolver ninguna fila al cliente.",
      "href": "/es/resources/support-center/knowledge-base/performance-optimization/check-query-processing-time-only",
      "category": "Rendimiento y optimización",
      "tags": [
        "Rendimiento y optimización"
      ]
    },
    {
      "id": "monitoring-debugging/collect-and-draw-traces",
      "title": "Cómo recopilar y visualizar una traza de consulta",
      "description": "Esta guía le muestra cómo recopilar y visualizar trazas de consultas con ClickHouse autogestionado, ya sea con métodos integrados o con Grafana. Esto resulta especialmente útil cuando trabaja con consultas complejas y necesita comprender los mecanismos internos de ejecución más allá de lo que ofrece EXPLAIN.",
      "href": "/es/resources/support-center/knowledge-base/monitoring-debugging/collect-and-draw-traces",
      "category": "Monitorización y depuración",
      "tags": [
        "Herramientas y utilidades"
      ]
    },
    {
      "id": "tables-schema/recreate-table-across-terminals",
      "title": "Cómo recrear rápidamente una tabla pequeña entre distintas terminales",
      "description": "Aprende a recrear rápidamente una tabla pequeña y sus datos entre distintas terminales mediante copiar y pegar en entornos de desarrollo.",
      "href": "/es/resources/support-center/knowledge-base/tables-schema/recreate-table-across-terminals",
      "category": "Tablas y esquema",
      "tags": [
        "Herramientas y utilidades"
      ]
    },
    {
      "id": "troubleshooting/recovering-from-corrupt-keeper-snapshot",
      "title": "Cómo recuperarse de una instantánea corrupta de Keeper",
      "description": "Artículo que describe cómo recuperarse de una instantánea corrupta de Keeper: cómo se manifiesta el problema, qué es una instantánea, dónde encontrarla y cuáles son las posibles estrategias de recuperación.",
      "href": "/es/resources/support-center/knowledge-base/troubleshooting/recovering-from-corrupt-keeper-snapshot",
      "category": "Resolución de problemas y errores",
      "tags": [
        "Solución de problemas"
      ]
    },
    {
      "id": "data-import-export/cannot-append-data-to-parquet-format",
      "title": "Cómo resolver el error \"Cannot Append Data in Parquet Format\" en ClickHouse",
      "description": "¿Te aparece el error \"Cannot append data in format Parquet to file\" en ClickHouse? Veamos cómo solucionarlo.",
      "href": "/es/resources/support-center/knowledge-base/data-import-export/cannot-append-data-to-parquet-format",
      "category": "Importación y exportación de datos",
      "tags": [
        "Errores y excepciones",
        "Formatos de datos"
      ]
    },
    {
      "id": "troubleshooting/certificate-verify-failed-error",
      "title": "Cómo resolver el error de verificación del certificado SSL en ClickHouse",
      "description": "Aprenda a resolver el error SSL CERTIFICATE_VERIFY_FAILED.",
      "href": "/es/resources/support-center/knowledge-base/troubleshooting/certificate-verify-failed-error",
      "category": "Resolución de problemas y errores",
      "tags": [
        "Seguridad y autenticación",
        "Errores y excepciones"
      ]
    },
    {
      "id": "troubleshooting/connection-timeout-remote-remoteSecure",
      "title": "Cómo resolver errores de tiempo de espera con las funciones de tabla `remote` y `remoteSecure`",
      "description": "Aprenda a corregir los errores de tiempo de espera al usar las funciones de tabla `remote` o `remoteSecure` en ClickHouse ajustando la configuración del tiempo de espera de conexión.",
      "href": "/es/resources/support-center/knowledge-base/troubleshooting/connection-timeout-remote-remoteSecure",
      "category": "Resolución de problemas y errores",
      "tags": [
        "Errores y excepciones"
      ]
    },
    {
      "id": "troubleshooting/exception-too-many-parts",
      "title": "Cómo resolver la excepción \"Too many parts\" en ClickHouse",
      "description": "Aprende a diagnosticar y resolver la excepción \"Too many parts\" agrupando las inserciones en lotes, usando inserciones asíncronas y eligiendo una clave de particionamiento adecuada.",
      "href": "/es/resources/support-center/knowledge-base/troubleshooting/exception-too-many-parts",
      "category": "Resolución de problemas y errores",
      "tags": [
        "Errores y excepciones"
      ]
    },
    {
      "id": "troubleshooting/restore-replica-after-storage-failure",
      "title": "Cómo restaurar una réplica tras un fallo de almacenamiento",
      "description": "En este artículo se explica cómo recuperar datos al usar tablas replicadas en bases de datos Atomic en ClickHouse cuando se pierde o se corrompe el disco o almacenamiento de una de las réplicas.",
      "href": "/es/resources/support-center/knowledge-base/troubleshooting/restore-replica-after-storage-failure",
      "category": "Resolución de problemas y errores",
      "tags": [
        "Implementaciones y escalado"
      ]
    },
    {
      "id": "queries-sql/using-array-join-to-extract-and-query-attributes",
      "title": "Cómo usar ARRAY JOIN para extraer y consultar atributos variables con claves y valores de Map",
      "description": "Ejemplo sencillo para ilustrar cómo usar ARRAY JOIN para extraer y consultar atributos variables con claves y valores de Map",
      "href": "/es/resources/support-center/knowledge-base/queries-sql/using-array-join-to-extract-and-query-attributes",
      "category": "Consultas y SQL",
      "tags": [
        "Funciones"
      ]
    },
    {
      "id": "tables-schema/exchangeStatementToSwitchTables",
      "title": "Cómo usar el comando EXCHANGE para intercambiar tablas",
      "description": "Cómo usar el comando EXCHANGE para intercambiar tablas",
      "href": "/es/resources/support-center/knowledge-base/tables-schema/exchangeStatementToSwitchTables",
      "category": "Tablas y esquema",
      "tags": [
        "Gestión de datos"
      ]
    },
    {
      "id": "integrations/node-js-example",
      "title": "Cómo usar NodeJS con @clickhouse/client",
      "description": "Aprende a usar @clickhouse/client en una aplicación Node.js para interactuar con ClickHouse y realizar consultas.",
      "href": "/es/resources/support-center/knowledge-base/integrations/node-js-example",
      "category": "Integraciones y bibliotecas de cliente",
      "tags": [
        "Clientes de lenguaje"
      ]
    },
    {
      "id": "materialized-views/how-to-use-parametrised-views",
      "title": "Cómo usar vistas parametrizadas en ClickHouse",
      "description": "Aprende a crear y consultar vistas parametrizadas en ClickHouse para segmentar datos dinámicamente en función de parámetros en tiempo de consulta.",
      "href": "/es/resources/support-center/knowledge-base/materialized-views/how-to-use-parametrised-views",
      "category": "Vistas materializadas y proyecciones",
      "tags": [
        "Casos de uso"
      ]
    },
    {
      "id": "queries-sql/compare-resultsets",
      "title": "Cómo validar si dos consultas devuelven el mismo conjunto de resultados",
      "description": "Aprende a validar que dos consultas de ClickHouse produzcan el mismo conjunto de resultados mediante funciones hash y técnicas de comparación.",
      "href": "/es/resources/support-center/knowledge-base/queries-sql/compare-resultsets",
      "category": "Consultas y SQL",
      "tags": [
        "Funciones"
      ]
    },
    {
      "id": "monitoring-debugging/check-query-cache-in-use",
      "title": "Cómo verificar el uso de la caché de consultas en ClickHouse",
      "description": "Aprende a comprobar si la caché de consultas se está utilizando en ClickHouse mediante los registros de nivel trace de `clickhouse-client` o comandos SQL.",
      "href": "/es/resources/support-center/knowledge-base/monitoring-debugging/check-query-cache-in-use",
      "category": "Monitorización y depuración",
      "tags": [
        "Rendimiento y optimización"
      ]
    },
    {
      "id": "troubleshooting/part-intersects-previous-part",
      "title": "DB::Exception: La parte XXXXX se solapa con la parte anterior YYYYY. Es un error o el resultado de una intervención manual en los datos de ZooKeeper.",
      "description": "Este artículo explica cómo resolver el error DB::Exception relacionado con partes solapadas en ClickHouse, a menudo causado por una condición de carrera o por una intervención manual en los datos de ZooKeeper.",
      "href": "/es/resources/support-center/knowledge-base/troubleshooting/part-intersects-previous-part",
      "category": "Resolución de problemas y errores",
      "tags": [
        "Errores y excepciones",
        "Tablas del sistema"
      ]
    },
    {
      "id": "setup-installation/difference-between-official-builds-and-3rd-party",
      "title": "Diferencias entre las compilaciones oficiales de ClickHouse y las compilaciones de terceros",
      "description": "Conozca las diferencias clave entre las compilaciones oficiales de ClickHouse y las compilaciones de terceros, incluidas las actualizaciones, la compatibilidad y las consideraciones de seguridad.",
      "href": "/es/resources/support-center/knowledge-base/setup-installation/difference-between-official-builds-and-3rd-party",
      "category": "Configuración e instalación",
      "tags": [
        "Conceptos"
      ]
    },
    {
      "id": "cloud-services/execute-system-queries-in-cloud",
      "title": "Ejecutar sentencias SYSTEM en todos los nodos de ClickHouse Cloud",
      "description": "Aprenda a usar `ON CLUSTER` y `clusterAllReplicas` para ejecutar sentencias SYSTEM y consultas en todos los nodos de un servicio de ClickHouse Cloud.",
      "href": "/es/resources/support-center/knowledge-base/cloud-services/execute-system-queries-in-cloud",
      "category": "Cloud",
      "tags": [
        "Implementaciones y escalado"
      ]
    },
    {
      "id": "data-import-export/json-extract-example",
      "title": "Ejemplo de JSON Extract",
      "description": "Un breve ejemplo de cómo extraer tipos básicos de JSON",
      "href": "/es/resources/support-center/knowledge-base/data-import-export/json-extract-example",
      "category": "Importación y exportación de datos",
      "tags": [
        "Formatos de datos"
      ]
    },
    {
      "id": "integrations/terraform-example",
      "title": "Ejemplo de Terraform: cómo usar la API de Cloud",
      "description": "Este ejemplo muestra cómo puedes usar Terraform para crear y eliminar clústeres mediante la API",
      "href": "/es/resources/support-center/knowledge-base/integrations/terraform-example",
      "category": "Integraciones y bibliotecas de cliente",
      "tags": [
        "Clientes nativos e interfaces"
      ]
    },
    {
      "id": "integrations/python-http-requests",
      "title": "Ejemplo rápido de Python con el módulo HTTP requests",
      "description": "Un ejemplo con Python y el módulo requests para escribir y leer datos en ClickHouse",
      "href": "/es/resources/support-center/knowledge-base/integrations/python-http-requests",
      "category": "Integraciones y bibliotecas de cliente",
      "tags": [
        "Clientes nativos e interfaces"
      ]
    },
    {
      "id": "troubleshooting/count-parts-by-type",
      "title": "Encontrar el número y tamaño de las partes anchas o compactas",
      "description": "Este artículo de la base de conocimientos muestra cómo encontrar el número de partes según el tipo de parte: ancha o compacta.",
      "href": "/es/resources/support-center/knowledge-base/troubleshooting/count-parts-by-type",
      "category": "Resolución de problemas y errores",
      "tags": [
        "Solución de problemas"
      ]
    },
    {
      "id": "integrations/ODBC-authentication-failed-error-using-PowerBI-CH-connector",
      "title": "Error de autenticación de ODBC al usar el conector ClickHouse para Power BI",
      "description": "Error de autenticación de ODBC al usar el conector ClickHouse para Power BI",
      "href": "/es/resources/support-center/knowledge-base/integrations/ODBC-authentication-failed-error-using-PowerBI-CH-connector",
      "category": "Integraciones y bibliotecas de cliente",
      "tags": [
        "Clientes nativos e interfaces",
        "Errores y excepciones"
      ]
    },
    {
      "id": "performance-optimization/query-max-execution-time",
      "title": "Establecer un límite para el tiempo de ejecución de una consulta",
      "description": "Cómo establecer un límite para el tiempo máximo de ejecución de una consulta",
      "href": "/es/resources/support-center/knowledge-base/performance-optimization/query-max-execution-time",
      "category": "Rendimiento y optimización",
      "tags": [
        "Gestión de Cloud",
        "Configuración"
      ]
    },
    {
      "id": "configuration-settings/alter-user-settings-exception",
      "title": "Excepción al modificar la configuración del usuario",
      "description": "Cómo gestionar una excepción generada al modificar la configuración del usuario",
      "href": "/es/resources/support-center/knowledge-base/configuration-settings/alter-user-settings-exception",
      "category": "Configuración y ajustes",
      "tags": [
        "Configuración",
        "Errores y excepciones"
      ]
    },
    {
      "id": "data-import-export/json-simple-example",
      "title": "Flujo de ejemplo sencillo para extraer datos JSON usando una tabla de aterrizaje con una vista materializada",
      "description": "Flujo de ejemplo sencillo para extraer datos JSON usando una tabla de aterrizaje con una vista materializada",
      "href": "/es/resources/support-center/knowledge-base/data-import-export/json-simple-example",
      "category": "Importación y exportación de datos",
      "tags": [
        "Formatos de datos"
      ]
    },
    {
      "id": "cloud-services/clickhouse-cloud-api-usage",
      "title": "Gestión de un servicio de ClickHouse Cloud con la API y cURL",
      "description": "Aprenda a iniciar, detener y reanudar un servicio de ClickHouse Cloud mediante endpoints de API y comandos de cURL.",
      "href": "/es/resources/support-center/knowledge-base/cloud-services/clickhouse-cloud-api-usage",
      "category": "Cloud",
      "tags": [
        "Administración de Cloud",
        "Herramientas y utilidades"
      ]
    },
    {
      "id": "tables-schema/schema-migration-tools",
      "title": "Herramientas de migración de esquemas para ClickHouse",
      "description": "Conozca las herramientas de migración de esquemas para ClickHouse y cómo gestionar la evolución de los esquemas de bases de datos a lo largo del tiempo.",
      "href": "/es/resources/support-center/knowledge-base/tables-schema/schema-migration-tools",
      "category": "Tablas y esquema",
      "tags": [
        "Herramientas y utilidades"
      ]
    },
    {
      "id": "performance-optimization/finding-expensive-queries-by-memory-usage",
      "title": "Identificación de consultas costosas según el uso de memoria en ClickHouse",
      "description": "Aprende a usar la tabla `system.query_log` para encontrar las consultas que más memoria consumen en ClickHouse, con ejemplos para configuraciones en clúster e independientes.",
      "href": "/es/resources/support-center/knowledge-base/performance-optimization/finding-expensive-queries-by-memory-usage",
      "category": "Rendimiento y optimización",
      "tags": [
        "Rendimiento y optimización"
      ]
    },
    {
      "id": "data-import-export/importing-geojason-with-nested-object-array",
      "title": "Importación de GeoJSON con un array de objetos profundamente anidado",
      "description": "Aprenda a importar archivos GeoJSON con arrays de objetos profundamente anidados en ClickHouse y a consultar los datos anidados de `feature`.",
      "href": "/es/resources/support-center/knowledge-base/data-import-export/importing-geojason-with-nested-object-array",
      "category": "Importación y exportación de datos",
      "tags": [
        "Formatos de datos"
      ]
    },
    {
      "id": "data-import-export/importing-and-working-with-json-array-objects",
      "title": "Importación y consulta de objetos en arrays JSON en ClickHouse",
      "description": "Aprende a importar objetos en arrays JSON a ClickHouse y a realizar consultas avanzadas con funciones JSON y operaciones con arrays.",
      "href": "/es/resources/support-center/knowledge-base/data-import-export/importing-and-working-with-json-array-objects",
      "category": "Importación y exportación de datos",
      "tags": [
        "Formatos de datos"
      ]
    },
    {
      "id": "performance-optimization/async-vs-optimize-read-in-order",
      "title": "Lectura síncrona de datos",
      "description": "El nuevo ajuste `allow_asynchronous_read_from_io_pool_for_merge_tree` permite que el número de hilos de lectura (streams) sea mayor que el número de hilos en el resto del pipeline de ejecución de la consulta.",
      "href": "/es/resources/support-center/knowledge-base/performance-optimization/async-vs-optimize-read-in-order",
      "category": "Rendimiento y optimización",
      "tags": [
        "Configuración",
        "Rendimiento y optimización"
      ]
    },
    {
      "id": "data-import-export/achieving-atomic-inserts",
      "title": "Lograr inserciones atómicas y consistencia entre múltiples tablas en ClickHouse Cloud",
      "description": "Cómo cargar datos de forma atómica y mantener la consistencia entre múltiples tablas en ClickHouse Cloud sin transacciones multisentencia, mediante tablas de staging y operaciones a nivel de partición.",
      "href": "/es/resources/support-center/knowledge-base/data-import-export/achieving-atomic-inserts",
      "category": "Importación y exportación de datos",
      "tags": [
        "Ingestión de datos",
        "buenas prácticas"
      ]
    },
    {
      "id": "configuration-settings/maximum-number-of-tables-and-databases",
      "title": "Límites máximos recomendados de bases de datos, tablas, particiones y partes en ClickHouse",
      "description": "Conozca los límites máximos recomendados para bases de datos, tablas, particiones y partes en un clúster de ClickHouse para garantizar un rendimiento óptimo.",
      "href": "/es/resources/support-center/knowledge-base/configuration-settings/maximum-number-of-tables-and-databases",
      "category": "Configuración y ajustes",
      "tags": [
        "Rendimiento y optimizaciones",
        "Implementaciones y escalado"
      ]
    },
    {
      "id": "performance-optimization/improve-map-performance",
      "title": "Mejorar el rendimiento de las búsquedas en Map en ClickHouse",
      "description": "Aprende a optimizar las búsquedas en columnas Map de ClickHouse para mejorar el rendimiento de las consultas materializando claves específicas como columnas independientes.",
      "href": "/es/resources/support-center/knowledge-base/performance-optimization/improve-map-performance",
      "category": "Rendimiento y optimización",
      "tags": [
        "Rendimiento y optimización"
      ]
    },
    {
      "id": "cloud-services/unable-to-access-cloud-service",
      "title": "No puedo acceder a un servicio de ClickHouse Cloud",
      "description": "Resolución de problemas de acceso a servicios de ClickHouse Cloud, incluida la configuración de la IP Access List",
      "href": "/es/resources/support-center/knowledge-base/cloud-services/unable-to-access-cloud-service",
      "category": "Cloud",
      "tags": [
        "Errores y excepciones",
        "Administración de Cloud"
      ]
    },
    {
      "id": "monitoring-debugging/profiling-clickhouse-with-llvm-xray",
      "title": "Perfilado de ClickHouse con XRay de LLVM",
      "description": "Aprende a perfilar ClickHouse con el perfilador de instrumentación XRay de LLVM, visualizar trazas y analizar el rendimiento.",
      "href": "/es/resources/support-center/knowledge-base/monitoring-debugging/profiling-clickhouse-with-llvm-xray",
      "category": "Monitorización y depuración",
      "tags": [
        "Rendimiento y optimización",
        "Herramientas y utilidades"
      ]
    },
    {
      "id": "security/set-role-not-persisting-in-sql-console",
      "title": "Por qué `SET ROLE` no se mantiene en la SQL Console de ClickHouse Cloud",
      "description": "Aprenda por qué `SET ROLE` no se mantiene en la SQL Console de ClickHouse Cloud y cómo asignar permisos persistentes por usuario.",
      "href": "/es/resources/support-center/knowledge-base/security/set-role-not-persisting-in-sql-console",
      "category": "Seguridad y control de acceso",
      "tags": [
        "Seguridad y autenticación",
        "Gestión de Cloud",
        "Solución de problemas"
      ]
    },
    {
      "id": "tables-schema/runbook-json",
      "title": "Runbook: esquema de JSON",
      "description": "Elige el enfoque de esquema adecuado para datos JSON en ClickHouse: columnas tipadas, híbrido, JSON nativo o almacenamiento como String",
      "href": "/es/resources/support-center/knowledge-base/tables-schema/runbook-json",
      "category": "Tablas y esquema",
      "tags": [
        "Runbooks",
        "Modelado de datos"
      ]
    },
    {
      "id": "performance-optimization/memory-limit-exceeded-for-query",
      "title": "Se ha superado el límite de memoria de la consulta",
      "description": "Solución de problemas de errores de límite de memoria superado en una consulta",
      "href": "/es/resources/support-center/knowledge-base/performance-optimization/memory-limit-exceeded-for-query",
      "category": "Rendimiento y optimización",
      "tags": [
        "Errores y excepciones"
      ]
    },
    {
      "id": "cloud-services/aws-privatelink-vpc-endpoint-service-for-msk-cluster",
      "title": "Servicio de endpoint de VPC de AWS PrivateLink para un clúster de MSK",
      "description": "Pasos de configuración para exponer un clúster de MSK a ClickPipes mediante servicios de endpoint de VPC de AWS PrivateLink.",
      "href": "/es/resources/support-center/knowledge-base/cloud-services/aws-privatelink-vpc-endpoint-service-for-msk-cluster",
      "category": "Cloud",
      "tags": [
        "Seguridad y autenticación",
        "Gestión de Cloud"
      ]
    },
    {
      "id": "troubleshooting/fix-developer-verification-error-in-macos",
      "title": "Soluciona el error de verificación del desarrollador en MacOS",
      "description": "Aprende a resolver el error de verificación del desarrollador en MacOS al ejecutar comandos de ClickHouse, ya sea con System Settings o desde la terminal.",
      "href": "/es/resources/support-center/knowledge-base/troubleshooting/fix-developer-verification-error-in-macos",
      "category": "Resolución de problemas y errores",
      "tags": [
        "Errores y excepciones"
      ]
    },
    {
      "id": "integrations/python-clickhouse-connect-example",
      "title": "Un ejemplo práctico de cliente de Python para conectarse al servicio de ClickHouse Cloud",
      "description": "Aprende a conectarte al servicio de ClickHouse Cloud desde Python con un ejemplo paso a paso que utiliza el driver clickhouse-connect.",
      "href": "/es/resources/support-center/knowledge-base/integrations/python-clickhouse-connect-example",
      "category": "Integraciones y bibliotecas de cliente",
      "tags": [
        "Clientes de lenguaje"
      ]
    },
    {
      "id": "queries-sql/filtered-aggregates",
      "title": "Uso de agregados filtrados en ClickHouse",
      "description": "Aprende a usar agregados filtrados en ClickHouse con los combinadores de agregación `-If` y `-Distinct` para simplificar la sintaxis de las consultas y mejorar el análisis.",
      "href": "/es/resources/support-center/knowledge-base/queries-sql/filtered-aggregates",
      "category": "Consultas y SQL",
      "tags": [
        "Funciones"
      ]
    },
    {
      "id": "general-faqs/use-clickhouse-for-log-analytics",
      "title": "Uso de ClickHouse para la analítica de logs",
      "description": "ClickHouse es popular para el análisis de logs y métricas gracias a sus capacidades de análisis en tiempo real. ¿Quieres saber más?",
      "href": "/es/resources/support-center/knowledge-base/general-faqs/use-clickhouse-for-log-analytics",
      "category": "General y preguntas frecuentes",
      "tags": [
        "Casos de uso"
      ]
    },
    {
      "id": "general-faqs/datalake",
      "title": "¿Admite ClickHouse los lagos de datos?",
      "description": "ClickHouse admite lagos de datos, incluidos Iceberg, Delta Lake, Apache Hudi, Apache Paimon, Hive",
      "href": "/es/resources/support-center/knowledge-base/general-faqs/datalake",
      "category": "General y preguntas frecuentes",
      "tags": []
    },
    {
      "id": "general-faqs/updates",
      "title": "¿ClickHouse admite actualizaciones en tiempo real?",
      "description": "ClickHouse admite actualizaciones ligeras en tiempo real",
      "href": "/es/resources/support-center/knowledge-base/general-faqs/updates",
      "category": "General y preguntas frecuentes",
      "tags": []
    },
    {
      "id": "general-faqs/federated",
      "title": "¿ClickHouse admite consultas federadas?",
      "description": "ClickHouse admite una amplia gama de consultas federadas e híbridas",
      "href": "/es/resources/support-center/knowledge-base/general-faqs/federated",
      "category": "General y preguntas frecuentes",
      "tags": []
    },
    {
      "id": "general-faqs/concurrency",
      "title": "¿ClickHouse admite consultas frecuentes y concurrentes?",
      "description": "ClickHouse admite QPS altos y alta concurrencia",
      "href": "/es/resources/support-center/knowledge-base/general-faqs/concurrency",
      "category": "General y preguntas frecuentes",
      "tags": []
    },
    {
      "id": "general-faqs/distributed-join",
      "title": "¿ClickHouse admite JOIN distribuidos?",
      "description": "ClickHouse admite JOIN distribuidos",
      "href": "/es/resources/support-center/knowledge-base/general-faqs/distributed-join",
      "category": "General y preguntas frecuentes",
      "tags": []
    },
    {
      "id": "cloud-services/multi-region-replication",
      "title": "¿ClickHouse admite la replicación multirregional?",
      "description": "Esta página responde a la pregunta de si ClickHouse admite la replicación multirregional",
      "href": "/es/resources/support-center/knowledge-base/cloud-services/multi-region-replication",
      "category": "Cloud",
      "tags": []
    },
    {
      "id": "security/row-column-policy",
      "title": "¿ClickHouse admite seguridad a nivel de fila y de columna?",
      "description": "Más información sobre las restricciones de acceso a nivel de fila y de columna en ClickHouse y ClickHouse Cloud, y sobre cómo implementar control de acceso basado en roles (RBAC) con políticas.",
      "href": "/es/resources/support-center/knowledge-base/security/row-column-policy",
      "category": "Seguridad y control de acceso",
      "tags": [
        "Seguridad y autenticación"
      ]
    },
    {
      "id": "general-faqs/cost-based",
      "title": "¿ClickHouse tiene un optimizador basado en costos?",
      "description": "ClickHouse tiene ciertos mecanismos de optimización basados en costos",
      "href": "/es/resources/support-center/knowledge-base/general-faqs/cost-based",
      "category": "General y preguntas frecuentes",
      "tags": []
    },
    {
      "id": "performance-optimization/optimize-final-vs-final",
      "title": "¿Cuál es la diferencia entre OPTIMIZE FINAL y FINAL?",
      "description": "Explica las diferencias entre OPTIMIZE FINAL y FINAL, y cuándo conviene usarlos o evitarlos.",
      "href": "/es/resources/support-center/knowledge-base/performance-optimization/optimize-final-vs-final",
      "category": "Rendimiento y optimización",
      "tags": [
        "Conceptos fundamentales de los datos"
      ]
    },
    {
      "id": "general-faqs/dependencies",
      "title": "¿Cuáles son las dependencias de terceros para ejecutar ClickHouse?",
      "description": "ClickHouse es autónomo y no tiene dependencias en tiempo de ejecución",
      "href": "/es/resources/support-center/knowledge-base/general-faqs/dependencies",
      "category": "General y preguntas frecuentes",
      "tags": []
    },
    {
      "id": "data-management/when-is-ttl-applied",
      "title": "¿Cuándo se aplican las reglas TTL y se puede controlar?",
      "description": "Las reglas TTL en ClickHouse acaban aplicándose, y puede controlar cuándo se ejecutan mediante la configuración `merge_with_ttl_timeout`. Aprenda a forzar la aplicación de TTL y a gestionar los hilos en segundo plano para su ejecución.",
      "href": "/es/resources/support-center/knowledge-base/data-management/when-is-ttl-applied",
      "category": "Gestión de datos",
      "tags": [
        "Conceptos fundamentales de los datos"
      ]
    },
    {
      "id": "cloud-services/change-billing-email",
      "title": "¿Cómo cambio mi contacto de facturación en ClickHouse Cloud?",
      "description": "Veamos cómo cambiar tu dirección de facturación en ClickHouse Cloud.",
      "href": "/es/resources/support-center/knowledge-base/cloud-services/change-billing-email",
      "category": "Cloud",
      "tags": [
        "Administración de Cloud"
      ]
    },
    {
      "id": "materialized-views/projection-example",
      "title": "¿Cómo confirmar si una proyección se usa en la consulta?",
      "description": "Aprende a comprobar si se usa una proyección en las consultas de ClickHouse probando con datos de muestra y usando EXPLAIN para verificar su uso.",
      "href": "/es/resources/support-center/knowledge-base/materialized-views/projection-example",
      "category": "Vistas materializadas y proyecciones",
      "tags": [
        "Modelado de datos"
      ]
    },
    {
      "id": "data-import-export/parquet-to-csv-json",
      "title": "¿Cómo convertir archivos Parquet a CSV o JSON?",
      "description": "Aprende a usar la herramienta `clickhouse-local` de ClickHouse para convertir fácilmente archivos Parquet a formatos CSV o JSON.",
      "href": "/es/resources/support-center/knowledge-base/data-import-export/parquet-to-csv-json",
      "category": "Importación y exportación de datos",
      "tags": [
        "Fuentes de datos",
        "Formatos de datos"
      ]
    },
    {
      "id": "security/remove-default-user",
      "title": "¿Cómo elimino el usuario `default`?",
      "description": "Aprende a eliminar el usuario `default` al ejecutar ClickHouse Server.",
      "href": "/es/resources/support-center/knowledge-base/security/remove-default-user",
      "category": "Seguridad y control de acceso",
      "tags": [
        "Administración del servidor"
      ]
    },
    {
      "id": "data-import-export/postgresql-to-parquet-csv-json",
      "title": "¿Cómo exportar datos de PostgreSQL a Parquet, CSV o JSON?",
      "description": "Aprende a exportar datos de PostgreSQL a los formatos Parquet, CSV o JSON con `clickhouse-local` mediante varios ejemplos.",
      "href": "/es/resources/support-center/knowledge-base/data-import-export/postgresql-to-parquet-csv-json",
      "category": "Importación y exportación de datos",
      "tags": [
        "Exportación de datos",
        "Formatos de datos"
      ]
    },
    {
      "id": "queries-sql/how-to-filter-a-clickhouse-table-by-an-array-column",
      "title": "¿Cómo filtrar una tabla de ClickHouse por una columna de tipo Array?",
      "description": "Artículo de la base de conocimientos sobre cómo filtrar una tabla de ClickHouse por una columna de tipo Array.",
      "href": "/es/resources/support-center/knowledge-base/queries-sql/how-to-filter-a-clickhouse-table-by-an-array-column",
      "category": "Consultas y SQL",
      "tags": [
        "Modelado de datos",
        "Funciones"
      ]
    },
    {
      "id": "data-import-export/json-import",
      "title": "¿Cómo importar JSON a ClickHouse?",
      "description": "Esta página muestra cómo importar JSON a ClickHouse",
      "href": "/es/resources/support-center/knowledge-base/data-import-export/json-import",
      "category": "Importación y exportación de datos",
      "tags": []
    },
    {
      "id": "queries-sql/how-to-insert-all-rows-from-another-table",
      "title": "¿Cómo insertar todas las filas de una tabla a otra?",
      "description": "Artículo de la base de conocimientos sobre cómo insertar todas las filas de una tabla a otra.",
      "href": "/es/resources/support-center/knowledge-base/queries-sql/how-to-insert-all-rows-from-another-table",
      "category": "Consultas y SQL",
      "tags": [
        "Ingestión de datos"
      ]
    },
    {
      "id": "setup-installation/install-clickhouse-windows10",
      "title": "¿Cómo instalo ClickHouse en Windows 10?",
      "description": "Aprende a instalar y probar ClickHouse en Windows 10 con WSL 2. Incluye la configuración, la solución de problemas y cómo ejecutar un entorno de prueba.",
      "href": "/es/resources/support-center/knowledge-base/setup-installation/install-clickhouse-windows10",
      "category": "Configuración e instalación",
      "tags": [
        "Herramientas y utilidades"
      ]
    },
    {
      "id": "data-management/read-consistency",
      "title": "¿Cómo lograr la consistencia en la lectura de datos en ClickHouse?",
      "description": "Aprende a garantizar la consistencia de los datos al leer desde ClickHouse, tanto si estás conectado al mismo nodo como a un nodo aleatorio.",
      "href": "/es/resources/support-center/knowledge-base/data-management/read-consistency",
      "category": "Gestión de datos",
      "tags": [
        "Rendimiento y optimización"
      ]
    },
    {
      "id": "general-faqs/how-do-i-contribute-code-to-clickhouse",
      "title": "¿Cómo puedo contribuir con código a ClickHouse?",
      "description": "ClickHouse es un proyecto de código abierto desarrollado en GitHub. Como es habitual, las instrucciones para contribuir se publican en el archivo CONTRIBUTING ubicado en la raíz del repositorio del código fuente.",
      "href": "/es/resources/support-center/knowledge-base/general-faqs/how-do-i-contribute-code-to-clickhouse",
      "category": "General y preguntas frecuentes",
      "tags": [
        "Comunidad"
      ]
    },
    {
      "id": "data-import-export/s3-export-data-year-month-folders",
      "title": "¿Cómo puedo hacer escritura particionada por año y mes en S3?",
      "description": "Aprenda a escribir datos particionados por año y mes en un bucket de S3 en ClickHouse, usando una estructura de ruta personalizada para organizar los datos.",
      "href": "/es/resources/support-center/knowledge-base/data-import-export/s3-export-data-year-month-folders",
      "category": "Importación y exportación de datos",
      "tags": [
        "Exportación de datos",
        "Clientes nativos e interfaces"
      ]
    },
    {
      "id": "performance-optimization/insert-select-settings-tuning",
      "title": "¿Cómo puedo resolver el error TOO MANY PARTS durante un INSERT...SELECT?",
      "description": "Soluciona el error TOO_MANY_PARTS en ClickHouse durante un `INSERT...SELECT` ajustando configuraciones avanzadas para bloques más grandes y aumentando los umbrales de partición.",
      "href": "/es/resources/support-center/knowledge-base/performance-optimization/insert-select-settings-tuning",
      "category": "Rendimiento y optimización",
      "tags": [
        "Configuración",
        "Errores y excepciones"
      ]
    },
    {
      "id": "data-import-export/kafka-clickhouse-json",
      "title": "¿Cómo puedo usar el nuevo tipo de datos JSON con Kafka?",
      "description": "Aprende a cargar mensajes JSON desde Apache Kafka directamente en una sola columna JSON de ClickHouse mediante el motor de tabla Kafka y el tipo de datos JSON.",
      "href": "/es/resources/support-center/knowledge-base/data-import-export/kafka-clickhouse-json",
      "category": "Importación y exportación de datos",
      "tags": [
        "Formatos de datos",
        "Ingestión de datos"
      ]
    },
    {
      "id": "monitoring-debugging/view-number-of-active-mutations",
      "title": "¿Cómo puedo ver el número de mutaciones activas o en cola?",
      "description": "Supervise el número de mutaciones activas o en cola en ClickHouse, especialmente al realizar operaciones `ALTER` o `UPDATE`. Use la tabla `system.mutations` para hacer un seguimiento de las mutaciones.",
      "href": "/es/resources/support-center/knowledge-base/monitoring-debugging/view-number-of-active-mutations",
      "category": "Monitorización y depuración",
      "tags": [
        "Tablas del sistema"
      ]
    },
    {
      "id": "cloud-services/ingest-failures-23-9-release",
      "title": "¿Cómo soluciono los fallos de ingesta tras la versión 23.9 de ClickHouse?",
      "description": "Aprenda a resolver los fallos de ingesta causados por una comprobación de grant más estricta introducida en ClickHouse 23.9 para tablas que usan `async_inserts`. Actualice los grant para corregir los errores.",
      "href": "/es/resources/support-center/knowledge-base/cloud-services/ingest-failures-23-9-release",
      "category": "Cloud",
      "tags": [
        "Errores y excepciones"
      ]
    },
    {
      "id": "monitoring-debugging/which-processes-are-currently-running",
      "title": "¿Cómo ver qué código se está ejecutando actualmente en un servidor?",
      "description": "ClickHouse proporciona herramientas de introspección como `system.stack_trace` para inspeccionar qué código se está ejecutando actualmente en cada hilo del servidor, lo que ayuda en la depuración y la monitorización del rendimiento.",
      "href": "/es/resources/support-center/knowledge-base/monitoring-debugging/which-processes-are-currently-running",
      "category": "Monitorización y depuración",
      "tags": [
        "Administración del servidor"
      ]
    },
    {
      "id": "general-faqs/separate-storage",
      "title": "¿Es posible desplegar ClickHouse con almacenamiento y cómputo separados?",
      "description": "Esta página responde a si es posible desplegar ClickHouse con almacenamiento y cómputo separados",
      "href": "/es/resources/support-center/knowledge-base/general-faqs/separate-storage",
      "category": "General y preguntas frecuentes",
      "tags": []
    },
    {
      "id": "tables-schema/delete-old-data",
      "title": "¿Es posible eliminar registros antiguos de una tabla de ClickHouse?",
      "description": "Esta página responde a la pregunta de si es posible eliminar registros antiguos de una tabla de ClickHouse",
      "href": "/es/resources/support-center/knowledge-base/tables-schema/delete-old-data",
      "category": "Tablas y esquema",
      "tags": []
    },
    {
      "id": "materialized-views/are-materialized-views-inserted-asynchronously",
      "title": "¿Las vistas materializadas se insertan de forma síncrona?",
      "description": "Este artículo de la base de conocimientos explora si las vistas materializadas se insertan de forma síncrona",
      "href": "/es/resources/support-center/knowledge-base/materialized-views/are-materialized-views-inserted-asynchronously",
      "category": "Vistas materializadas y proyecciones",
      "tags": [
        "Modelado de datos"
      ]
    },
    {
      "id": "monitoring-debugging/why-default-logging-verbose",
      "title": "¿Por qué el registro de ClickHouse es tan verboso de forma predeterminada?",
      "description": "Descubre por qué los desarrolladores de ClickHouse decidieron establecer, de forma predeterminada, un nivel de registro verboso.",
      "href": "/es/resources/support-center/knowledge-base/monitoring-debugging/why-default-logging-verbose",
      "category": "Monitorización y depuración",
      "tags": [
        "Configuración"
      ]
    },
    {
      "id": "data-management/dictionaries-consistent-state",
      "title": "¿Por qué no puedo ver mis datos en un diccionario de ClickHouse Cloud?",
      "description": "Existe un problema por el que es posible que los datos de los diccionarios no sean visibles inmediatamente después de crearlos.",
      "href": "/es/resources/support-center/knowledge-base/data-management/dictionaries-consistent-state",
      "category": "Gestión de datos",
      "tags": [
        "Administración de Cloud",
        "Modelado de datos"
      ]
    },
    {
      "id": "performance-optimization/why-is-my-primary-key-not-used",
      "title": "¿Por qué no se usa mi clave primaria? ¿Cómo puedo comprobarlo?",
      "description": "Aborda una razón común por la que no se utiliza la clave primaria en la ordenación y cómo podemos comprobarlo",
      "href": "/es/resources/support-center/knowledge-base/performance-optimization/why-is-my-primary-key-not-used",
      "category": "Rendimiento y optimización",
      "tags": [
        "Rendimiento y optimizaciones"
      ]
    },
    {
      "id": "general-faqs/mapreduce",
      "title": "¿Por qué no usar algo como MapReduce?",
      "description": "Esta página explica por qué usar ClickHouse en lugar de MapReduce",
      "href": "/es/resources/support-center/knowledge-base/general-faqs/mapreduce",
      "category": "General y preguntas frecuentes",
      "tags": []
    },
    {
      "id": "general-faqs/why-recommend-clickhouse-keeper-over-zookeeper",
      "title": "¿Por qué se recomienda ClickHouse Keeper en lugar de ZooKeeper?",
      "description": "ClickHouse Keeper ofrece mejoras frente a ZooKeeper, como un menor uso de espacio en disco, una recuperación más rápida y un menor consumo de memoria, lo que se traduce en un mejor rendimiento para los clusters de ClickHouse.",
      "href": "/es/resources/support-center/knowledge-base/general-faqs/why-recommend-clickhouse-keeper-over-zookeeper",
      "category": "General y preguntas frecuentes",
      "tags": [
        "Conceptos básicos de datos"
      ]
    },
    {
      "id": "general-faqs/key-value",
      "title": "¿Puedo usar ClickHouse como almacenamiento de clave-valor?",
      "description": "Responde a la pregunta frecuente de si ClickHouse puede usarse como almacenamiento de clave-valor.",
      "href": "/es/resources/support-center/knowledge-base/general-faqs/key-value",
      "category": "General y preguntas frecuentes",
      "tags": []
    },
    {
      "id": "general-faqs/time-series",
      "title": "¿Puedo usar ClickHouse como base de datos de series temporales?",
      "description": "Página que describe cómo usar ClickHouse como base de datos de series temporales",
      "href": "/es/resources/support-center/knowledge-base/general-faqs/time-series",
      "category": "General y preguntas frecuentes",
      "tags": []
    },
    {
      "id": "general-faqs/who-is-using-clickhouse",
      "title": "¿Quién usa ClickHouse?",
      "description": "Describe quién usa ClickHouse",
      "href": "/es/resources/support-center/knowledge-base/general-faqs/who-is-using-clickhouse",
      "category": "General y preguntas frecuentes",
      "tags": []
    },
    {
      "id": "general-faqs/olap",
      "title": "¿Qué es OLAP?",
      "description": "Una explicación de qué es Online Analytical Processing",
      "href": "/es/resources/support-center/knowledge-base/general-faqs/olap",
      "category": "General y preguntas frecuentes",
      "tags": []
    },
    {
      "id": "general-faqs/columnar-database",
      "title": "¿Qué es una base de datos columnar?",
      "description": "Una base de datos columnar almacena los datos de cada columna de forma independiente. Esto permite leer del disco solo los datos de las columnas que se usan en una consulta determinada.",
      "href": "/es/resources/support-center/knowledge-base/general-faqs/columnar-database",
      "category": "General y preguntas frecuentes",
      "tags": [
        "Conceptos fundamentales de datos"
      ]
    },
    {
      "id": "integrations/oracle-odbc",
      "title": "¿Qué ocurre si tengo problemas de codificación al usar Oracle a través de ODBC?",
      "description": "Esta página ofrece orientación sobre qué hacer si tiene problemas de codificación al usar Oracle a través de ODBC",
      "href": "/es/resources/support-center/knowledge-base/integrations/oracle-odbc",
      "category": "Integraciones y bibliotecas de cliente",
      "tags": []
    },
    {
      "id": "general-faqs/dbms-naming",
      "title": "¿Qué significa \"ClickHouse\"?",
      "description": "Aprende qué significa \"ClickHouse\"",
      "href": "/es/resources/support-center/knowledge-base/general-faqs/dbms-naming",
      "category": "General y preguntas frecuentes",
      "tags": []
    },
    {
      "id": "general-faqs/ne-tormozit",
      "title": "¿Qué significa “не тормозит”?",
      "description": "Esta página explica qué significa \"Не тормозит\"",
      "href": "/es/resources/support-center/knowledge-base/general-faqs/ne-tormozit",
      "category": "General y preguntas frecuentes",
      "tags": []
    },
    {
      "id": "general-faqs/sql",
      "title": "¿Qué sintaxis SQL admite ClickHouse?",
      "description": "ClickHouse admite el 100 % de la sintaxis SQL",
      "href": "/es/resources/support-center/knowledge-base/general-faqs/sql",
      "category": "General y preguntas frecuentes",
      "tags": []
    },
    {
      "id": "setup-installation/production",
      "title": "¿Qué versión de ClickHouse usar en producción?",
      "description": "Esta página ofrece orientación sobre qué versión de ClickHouse usar en producción",
      "href": "/es/resources/support-center/knowledge-base/setup-installation/production",
      "category": "Configuración e instalación",
      "tags": []
    },
    {
      "id": "queries-sql/pivot",
      "title": "¿Se puede hacer PIVOT en ClickHouse?",
      "description": "ClickHouse no tiene una cláusula PIVOT, pero podemos aproximarnos a esta funcionalidad usando combinadores de funciones de agregación. Veamos cómo hacerlo con el conjunto de datos de precios de la vivienda en el Reino Unido.",
      "href": "/es/resources/support-center/knowledge-base/queries-sql/pivot",
      "category": "Consultas y SQL",
      "tags": [
        "Modelado de datos",
        "Conceptos básicos de datos"
      ]
    },
    {
      "id": "general-faqs/vector-search",
      "title": "¿Se puede usar ClickHouse para la búsqueda vectorial?",
      "description": "Aprende a usar ClickHouse para la búsqueda vectorial, incluido el almacenamiento de embeddings y las búsquedas con funciones de distancia como la similitud de coseno.",
      "href": "/es/resources/support-center/knowledge-base/general-faqs/vector-search",
      "category": "General y preguntas frecuentes",
      "tags": [
        "Casos de uso",
        "Conceptos"
      ]
    }
  ]
};
